name: Generate documentation
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Generate documentation
      run: pip install pycco && find . -name "*.py" -execdir pycco {} -d docs/source/python/ \;
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/source/python/
        git commit -m "cron: documentation generated"
        git push origin HEAD:master
